name: 03-workflows-runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the runner OS
              run:  |
                echo "This job is running on ${{ runner.os }} runner"
                echo "The runner is hosted by ${{ runner.name }}"
                echo "The runner architecture is ${{ runner.arch }}"