name: 04 - Using Actions 
  
on: push 

jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:     
       working-directory: ./04-using-actions
    # 0 check out the code from the repository
    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
      - name: Setup_Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install_deps_and_run_tests
        run: npm ci   
      - name: Run_lint
        run: npm run lint 

    # 1 installl deps for react 

    # 2 excute automated test 
